export const ErrorCode = {
  // Common/system
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Auth/session/user
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
  REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_REVOKED: 'SESSION_REVOKED',

  // Organization/workspace
  ORGANIZATION_REQUIRED: 'ORGANIZATION_REQUIRED',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  ORGANIZATION_ACCESS_DENIED: 'ORGANIZATION_ACCESS_DENIED',
  ORGANIZATION_MEMBER_NOT_FOUND: 'ORGANIZATION_MEMBER_NOT_FOUND',
  ORGANIZATION_INVITATION_NOT_FOUND: 'ORGANIZATION_INVITATION_NOT_FOUND',
  ORGANIZATION_INVITATION_ALREADY_USED: 'ORGANIZATION_INVITATION_ALREADY_USED',

  // Documents
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_NOT_EDITABLE: 'DOCUMENT_NOT_EDITABLE',
  DOCUMENT_ALREADY_SENT: 'DOCUMENT_ALREADY_SENT',
  DOCUMENT_ALREADY_COMPLETED: 'DOCUMENT_ALREADY_COMPLETED',
  DOCUMENT_CANCELLED: 'DOCUMENT_CANCELLED',
  DOCUMENT_SEND_REQUIREMENTS_NOT_MET: 'DOCUMENT_SEND_REQUIREMENTS_NOT_MET',
  DOCUMENT_DELETE_NOT_ALLOWED: 'DOCUMENT_DELETE_NOT_ALLOWED',

  // File/storage/PDF
  FILE_REQUIRED: 'FILE_REQUIRED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
  STORAGE_DOWNLOAD_URL_FAILED: 'STORAGE_DOWNLOAD_URL_FAILED',
  PDF_PROCESSING_FAILED: 'PDF_PROCESSING_FAILED',
  PDF_ENCRYPTED_UNSUPPORTED: 'PDF_ENCRYPTED_UNSUPPORTED',
  PDF_PAGE_COUNT_FAILED: 'PDF_PAGE_COUNT_FAILED',
  PDF_TEXT_EXTRACTION_FAILED: 'PDF_TEXT_EXTRACTION_FAILED',

  // Document fields
  DOCUMENT_FIELD_NOT_FOUND: 'DOCUMENT_FIELD_NOT_FOUND',
  DOCUMENT_FIELD_INVALID_POSITION: 'DOCUMENT_FIELD_INVALID_POSITION',
  DOCUMENT_FIELD_RECIPIENT_REQUIRED: 'DOCUMENT_FIELD_RECIPIENT_REQUIRED',
  DOCUMENT_FIELD_TYPE_UNSUPPORTED: 'DOCUMENT_FIELD_TYPE_UNSUPPORTED',

  // Recipients
  RECIPIENT_NOT_FOUND: 'RECIPIENT_NOT_FOUND',
  RECIPIENT_ALREADY_EXISTS: 'RECIPIENT_ALREADY_EXISTS',
  RECIPIENT_REQUIRED: 'RECIPIENT_REQUIRED',
  RECIPIENT_ALREADY_SIGNED: 'RECIPIENT_ALREADY_SIGNED',
  RECIPIENT_EMAIL_INVALID: 'RECIPIENT_EMAIL_INVALID',
  RECIPIENT_ROLE_NOT_ELIGIBLE: 'RECIPIENT_ROLE_NOT_ELIGIBLE',
  RECIPIENT_ROLE_CHANGE_REQUIRES_FIELD_REASSIGNMENT:
    'RECIPIENT_ROLE_CHANGE_REQUIRES_FIELD_REASSIGNMENT',

  // Signing
  SIGNING_REQUEST_NOT_FOUND: 'SIGNING_REQUEST_NOT_FOUND',
  SIGNING_TOKEN_INVALID: 'SIGNING_TOKEN_INVALID',
  SIGNING_TOKEN_EXPIRED: 'SIGNING_TOKEN_EXPIRED',
  SIGNING_ALREADY_SUBMITTED: 'SIGNING_ALREADY_SUBMITTED',
  SIGNING_REQUIRED_FIELDS_MISSING: 'SIGNING_REQUIRED_FIELDS_MISSING',
  SIGNING_SUBMISSION_INVALID: 'SIGNING_SUBMISSION_INVALID',
  SIGNING_REQUEST_REVOKED: 'SIGNING_REQUEST_REVOKED',

  // Audit
  AUDIT_EVENT_NOT_FOUND: 'AUDIT_EVENT_NOT_FOUND',
  AUDIT_LOG_UNAVAILABLE: 'AUDIT_LOG_UNAVAILABLE',

  // AI
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_USAGE_LIMIT_EXCEEDED: 'AI_USAGE_LIMIT_EXCEEDED',
  AI_ANALYSIS_NOT_FOUND: 'AI_ANALYSIS_NOT_FOUND',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  AI_DOCUMENT_TEXT_UNAVAILABLE: 'AI_DOCUMENT_TEXT_UNAVAILABLE',
  AI_OPERATION_NOT_SUPPORTED: 'AI_OPERATION_NOT_SUPPORTED',

  // Billing/usage
  PLAN_LIMIT_EXCEEDED: 'PLAN_LIMIT_EXCEEDED',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  CHECKOUT_FAILED: 'CHECKOUT_FAILED',
  BILLING_PROVIDER_ERROR: 'BILLING_PROVIDER_ERROR',
  USAGE_RECORD_FAILED: 'USAGE_RECORD_FAILED',

  // Jobs/idempotency/webhooks
  JOB_NOT_FOUND: 'JOB_NOT_FOUND',
  JOB_FAILED: 'JOB_FAILED',
  JOB_NOT_READY: 'JOB_NOT_READY',
  JOB_CANCELLED: 'JOB_CANCELLED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  IDEMPOTENCY_REPLAY_IN_PROGRESS: 'IDEMPOTENCY_REPLAY_IN_PROGRESS',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_EVENT_UNSUPPORTED: 'WEBHOOK_EVENT_UNSUPPORTED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
